add zsh completion

diff --git a/scripts/installfiles.sh.in b/scripts/installfiles.sh.in
--- a/scripts/installfiles.sh.in
+++ b/scripts/installfiles.sh.in
@@ -5,81 +5,90 @@ if [[ $OPENSWITCHER_INSTALL_WITH_DPKG != 1 ]]; then
 	mkdir -p "/usr/local/lib/openswitcher/scripts/"
 	find "scripts/" -type f -name "*.sh" -exec cp -t "/usr/local/lib/openswitcher/scripts/" {} +
 	find "/usr/local/lib/openswitcher/scripts/" -type f -exec chmod +x {} +
+	find "scripts/" -type f -name "_openswitcher" -exec cp -t "/usr/local/lib/openswitcher/scripts/" {} +
 fi
 
 add_standart_combination() 
 {
-    if [ "$1" -eq 1 ]; then
-        if ! grep -q "$default_combination" "$file"; then
-			echo "Setting the standard keyboard shortcut to run openswitcher.sh."
-			echo "$default_combination" >> "$file"
-			echo "Set the configuration you need to run openswitcher.sh."
-        else
-            echo "Standard keyboard shortcut found."
-        fi
-    else
+	if [ ! -f "$file" ]; then
+		echo "File $file not found."
 		echo "Installing the standard $file."
 		mkdir "$XDG_CONFIG_HOME/actkbd"
 		touch "$file"
 		echo "Setting the standard keyboard shortcut to run openswitcher.sh."
 		echo "$default_combination" >> "$file"
 		echo "Set the configuration you need to run openswitcher.sh."
-    fi
-    
+	else
+		echo "File $file foud."
+		if ! grep -q "$default_combination" "$file"; then
+			echo "Setting the standard keyboard shortcut to run openswitcher.sh."
+			echo "$default_combination" >> "$file"
+			echo "Set the configuration you need to run openswitcher.sh."
+        else
+            echo "Standard keyboard shortcut found."
+        fi
+	fi    
 }
 
 add_standart_autostart()
 {   
-    if [ "$1" -eq 1 ]; then
-        if ! grep -q "$default_autostart_actkbd" "$file"; then
+	if [ ! -f "$file" ]; then
+		echo "File $file not found."
+		echo "Copying the standard /etc/X11/xinit/xinitrc to $file."
+		cp /etc/X11/xinit/xinitrc "$file"
+		echo "Installation of a standard autostart."
+		echo "$default_autostart_actkbd" >> "$file"
+	else
+		echo "File $file found."
+		if ! grep -q "$default_autostart_actkbd" "$file"; then
 			echo "Installation of a standard autostart."
 			echo "$default_autostart_actkbd" >> "$file"
         else
             echo "Standard autostart found."
         fi
-    else
-		echo "Copying the standard /etc/X11/xinit/xinitrc to $file."
-		cp /etc/X11/xinit/xinitrc "$file"
-		echo "Installation of a standard autostart."
-		echo "$default_autostart_actkbd" >> "$file"
-    fi
-    
+	fi    
 }
 
 # Check requested files
 for file in "${required_files[@]}"; do
 
-	if [ "$file" = "$XDG_CONFIG_HOME/actkbd/actkbd.conf" ]; then
-		if [ ! -f "$file" ]; then
-			echo "File $file not found."
-			add_standart_combination 0
-		else
-			echo "File $file foud."
-			add_standart_combination 1
-		fi
-
-	elif [ "$file" = "$HOME_USER/.xinitrc" ]; then
-		if [ ! -f "$file" ]; then
-			echo "File $file not found."
-			add_standart_autostart 0
-		else
-			echo "File $file foud."
-			add_standart_autostart 1
-		fi
-
-	elif [ "$file" = "/etc/bash_completion.d/openswitcher_autocomplete.sh" ]; then
-		if [ ! -f "$file" ]; then
-			echo "File $file not found."
-			echo "Installing /etc/bash_completion.d/openswitcher_autocomplete.sh"
-			if [[ $OPENSWITCHER_INSTALL_WITH_DPKG == 1 ]]; then
-				cp "/usr/lib/openswitcher/scripts/openswitcher_autocomplete.sh" "/etc/bash_completion.d/"
+	case "$file" in
+		"$XDG_CONFIG_HOME/actkbd/actkbd.conf")
+			add_standart_combination
+			;;
+		"$HOME_USER/.xinitrc")
+			add_standart_autostart
+			;;
+		"/etc/bash_completion.d/openswitcher_autocomplete.sh")
+			if [ ! -f "$file" ]; then
+				echo "File $file not found."
+				echo "Installing $file"
+				if [[ $OPENSWITCHER_INSTALL_WITH_DPKG == 1 ]]; then
+					cp "/usr/lib/openswitcher/scripts/openswitcher_autocomplete.sh" "$file"
+				else
+					cp "/usr/local/lib/openswitcher/scripts/openswitcher_autocomplete.sh" "$file"
+				fi
 			else
-				cp "/usr/local/lib/openswitcher/scripts/openswitcher_autocomplete.sh" "/etc/bash_completion.d/"
+				echo "File $file foud."
 			fi
-		else
-			echo "File $file foud."
-		fi
-	fi
+			;;
+		"/usr/share/zsh/functions/Completion/X/_openswitcher")
+			if [ ! -f "$file" ]; then
+				echo "File $file not found."
+				echo "Installing $file"
+				if [[ $OPENSWITCHER_INSTALL_WITH_DPKG == 1 ]]; then
+					cp "/usr/lib/openswitcher/scripts/_openswitcher" "$file"
+				else
+					cp "/usr/local/lib/openswitcher/scripts/_openswitcher" "$file"
+				fi
+			else
+				echo "File $file foud."
+			fi
+			;;
+		*)
+			
+			;;
+	esac
 
 done
 
